### ISSUE TITLE
MKR data storage folder hierarchy

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#1]
Need to create hierarchy for saving data from MKR.

Data -> vehicle_name -> test_type -> datetimestamp

**Comment by spencerharro** [comment]
Currently storing vibration data in text files labeled A1, A2, etc. Placing the text files in the following directory: /home/pi/ava/vehicle_profiles/Baseline-Idle
Need to make a change to add the vehicle name.

**Comment by sfreder** [comment]
Currently storing vibration data in text files labeled A1, A2, etc. Placing the text files in the following directory: /home/pi/ava/vehicle_profiles/Baseline-Idle
Need to make a change to add the vehicle name.

**Comment by spencerharro** [comment]
Vehicle Name - Spencer's car
Test Types -> Baseline-Idle, Baseline-Steadyspeed, Trouble-atidle, Troubleatsteady
- Baseline-Idle: AC on/off -> raw files
- Steadyspeed: 10 20 30 40 50 -> raw files
- Trouble at idle: Ac on/off -> timestamped folders -> raw data
- Touble at steady: 10 20 30 40 50 -> timestamped folders -> raw data

**Comment by sfreder** [comment]
Made progress here too. the branch directory_for-_data_files is where I am working.  I made a typo and added an extra hyphen to the branch name.  oops.

**Comment by spencerharro** [comment]
https://multiplestates.wordpress.com/2015/02/05/rename-a-local-and-remote-branch-in-git/

**Comment by sfreder** [comment]
Thanks for the link. I'll fix it tomorrow.

**Comment by sfreder** [comment]
The rest of this issue will be resolved when the signal processing is fully implemented.
