### ISSUE TITLE
Integrate data analysis / comparison code

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#10]
Integrate Steve's data analysis and comparison code in the post-test questions page backend.  Prepare data for presentation on Results page.

**Comment by sfreder** [comment]
Beginning work on this 3-7-17

**Comment by sfreder** [comment]
Signal processing code complete. Beginning comparison code.  Considering a calculation based on number of peaks that are 1.5 times the signal average.  Then weighting the peaks based on how close they are to the comparison data.  (Frequency and magnitude)

**Comment by sfreder** [comment]
I have a strategy working for comparison. I will start a branch for it.

**Comment by sfreder** [comment]
Confident that I have the necessary parameters for success. I have to catch up on other merge's to make sure I my code is up to date before proceeding.
