### ISSUE TITLE
standardized directory

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#2]
Convert the many `os.chdir(filepath_goes_here)` from specific filepaths to a variable.  Should allow easy variable changes when ava app is run on different platforms than RSPi.

**Comment by sfreder** [comment]
Currently storing vibration data in text files labeled A1, A2, etc.  Placing the text files in the following directory: /home/pi/ava/vehicle_profiles/Baseline-Idle  
Need to make a change to add the vehicle name.

**Comment by spencerharro** [comment]
path is just /home/pi/ava...then add on from here

**Comment by spencerharro** [comment]
@sfreder Not super time-sensitive, but wondering if at some point you can include some new sample data from your vehicles in Google Drive.  Would help to see the data in the anticipated folder structure to help upcoming programming.

**Comment by sfreder** [comment]
This is what I had in mind:  /home/pi/ava/vehicle_profiles/Steve's_Toyota/Baseline-Idle/Three_Axes1.txt
and:     /home/pi/ava/vehicle_profiles/Steve's_Toyota/Baseline-SS-60/Three_Axes1.txt
Do you want me to make these directories and push them up on a branch?

**Comment by spencerharro** [comment]
Either that or just post other data samples in a similar way sometime to Drive and I can work it into the repo.

**Comment by sfreder** [comment]
I placed 3 folders of raw data in the data folder under AVA central data storage.  I don't have files of the processed data at the moment.

**Comment by spencerharro** [comment]
Thanks - this is great for now

**Comment by sfreder** [comment]
@spencerharro There doesn't seem to be a branch for this issue yet.  I am going to create one and then push a change.  The change effects all of the pages.  What it does is list the parent directory once in the home page then save it to the json file, the home page sets the directory and all of the pages stay in that directory.  The json files also remain in the parent directory.  Individual widgets then access directory information from the json file if necessary and only access data in other directories without changing the directory.  So references to the parent directory are deleted from most pages.  The files will be pushed within about 30 minutes so you can review the work.

**Comment by sfreder** [comment]
Changes have been pushed.  I know I was going to work on a different issue but this helps me move to signal processing because I have to create several files and folders.

**Comment by sfreder** [comment]
I believe this portion of the directory standardization is done.
