### ISSUE TITLE
Warnings for existing baseline files. Unique naming for diagnostic files

### ISSUE THREAD

**Issue by sfreder** [vibrainium-analytics/ava#36]
- [ ] The user needs to be informed when the baseline exists so that they don't accidentally overwrite it.

 

- [x] The diagnostic files need a unique naming system (maybe a time stamp) so that they aren't accidentally overwritten.

**Comment by spencerharro** [comment]
@sfreder This covers the second item (timestamp), right?  So what remains is avoiding a baseline overwrite.
![screen shot 2017-03-23 at 7 57 04 pm](https://cloud.githubusercontent.com/assets/13437563/24275036/e8b6eaca-1002-11e7-8d50-196783ad5267.png)

**Comment by sfreder** [comment]
I think for searching and viewing purposes me may have to drop the time stamp and just do the date.  If there is more than one for a date then we should number them sequentially.  
Ex Mar-23-1   Mar-23-2
To answer your original question.  Yes this is the code that added the time stamp.

**Comment by sfreder** [comment]
Diagnostic file naming system is underway.  Historical trouble uses a sequential naming system while trouble that does not match historical data is called unknown_trouble and time stamped.
Diagnostic tests that match historical data or baselines and named after the profile that they match along with the percent match and a time stamp.

**Comment by spencerharro** [comment]
Since the naming is from the closest matching file, maybe we don't need to
sort the files in the list boxes. How about putting current test in Plot 1
automatically, and closest matching test automatically in Plot 2? Then give
all of the other possible plots (in no particular order) as alternative
options in drop down.

**Comment by sfreder** [comment]
Sounds like a good solution.  I haven't been able to follow the code on the plot page very well so I don't know how you choose what the list boxes are pre-populated with.

**Comment by spencerharro** [comment]
So far they pre-populate with everything that doesn't say "baseline" in the
directory name.

**Comment by spencerharro** [comment]
Then the baseline toggle picks the corresponding baseline to show based on
the Plot 1 drop down. I need to change this

**Comment by sfreder** [comment]
I believe diagnostic file naming is done. I will work on baseline exists warning box now.
