### ISSUE TITLE
Toggle Baseline Plot

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#44]
Checkbox in plot controls to enable toggling of baseline plot.
- [x] Only include baseline for currently selected test type (examine json file)
- [x] Add checkbox
- [x] Remove baseline tests from plot selection dropdowns.

**Comment by spencerharro** [comment]
Working on this now 3-22-17

**Comment by spencerharro** [comment]
@beleson In branch [Plots/Toggle_Baseline](https://github.com/vibrainium-analytics/ava/tree/Plots/Toggle_Baseline) are the temporary workings for a checkbox in the Plot Page to show the baseline plot.  Backend code is temporary (multiplies one of the data sets by 2 for display, not linked to any actual baseline file).  Wanted you to be able to see this for layout purposes.  If you have a better way to display it, go ahead and push any changes up and I will add them into subsequent updates

**Comment by spencerharro** [comment]
@sfreder Can you expand on this list of folders that might be anticipated in a vehicle directory?  I'm trying to make sure the plot page accounts for how we are setting this up.

**Example**
- Baseline-Idle
- Baseline-10
- Baseline-60
- Trouble-Idle
- Trouble-10
- Trouble2-10

**Comment by sfreder** [comment]
running tests right now. when I am done I will send you the entire folder for my car with all the subfolders and data in it.

**Comment by spencerharro** [comment]
#64 Addresses latest updates.

Still to do:

- [ ] Link Plot 1 dropdown to latest test (automatically selected at top)
- [x] Link Plot 2 dropdown to list of closest matching tests (not including test selected in Plot 1 dropdown)

**Comment by spencerharro** [comment]
@sfreder Where do you anticipate storing the percent match of the current test to all other tests?  I was thinking of ordering data in the plot selection dropdowns based on most-relevant to least-relevant.

**Comment by sfreder** [comment]
I just completed the code that would find the best match but I really don't know how to send that information to the plot page.  Any suggestions you have would help.

**Comment by spencerharro** [comment]
How about this - the comparison code could loop through each possible directory, then order the directories from highest to lowest percent match.  Then we pass that list of directories to the plot page as an array of strings, and it displays the plot choices in that same order.  This way no saving of that percent match is necessary

**Comment by spencerharro** [comment]
Alternatively, we save a text file with the possible directories ordered by closest percent match.  This gets saved in the file of the current test.  Then, when this test is selected in the first dropdown on the plot page, the app automatically suggests in the second dropdown the closest matching directories (based on that text file).

Any tests completed since that text file was created are ignored (or the new FFT directories complete a percent match calculation in case a closer match exists)

**Comment by sfreder** [comment]
I'll work on sorting when #72 is approved

**Comment by sfreder** [comment]
I have created a file called match.json which appears in the unknown trouble file.  The code to update the .json has not been written so don't simulate a test.  Just use the file to populate the plot drop downs and test the plotting abilities.  This is all I have time for today, hopefully I can do more tomorrow

**Comment by spencerharro** [comment]
Note to self - Use this sort strategy:
`
x = {3:2,2:1,1:5}
sorted(x.items(), key=lambda kv: kv[1])  # Items returns a list of `(key,value)`-pairs
[(2, 1), (3, 2), (1, 5)]`

**Comment by spencerharro** [comment]
Starting work on this 4-30-17

**Comment by spencerharro** [comment]
#76 Shows latest progress

**Comment by spencerharro** [comment]
Going to call this done for now and start over with a new issue for final fixes
