### ISSUE TITLE
Data collection timestamp

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#48]
There are a few locations where we could include a timestamp for data collection.

- Directly in data collection folder
- In a json file within the data collection directory (Spencer's Car -> Trouble Test 1 -> timestamp.json
- In the vehicle profile json file, could include a list of tests along with timestamps.

Any thoughts?

**Comment by sfreder** [comment]
Actually I am looking at this is two ways.  First when a diagnostic test is run it would be like this:
Steve's_Toyota/Diagnostic-Idle/timestamp/(text files)
and historical trouble data would be like this:
Steve's_Toyota/Trouble-Idle/Alt_Belt/(text files)
This way diagnostic tests remain in one folder and historical troubles are in another folder.  If the diagnostic test matches the an existing trouble, baseline, or the baseline does not exist, then the files remain in the diagnostic file.
If the diagnostic does not match existing data it and the baseline exists it will be placed in another folder like this:
Steve's_Toyota/Trouble-Idle/Unknown-timestamp/(text files)

let me know what you think

**Comment by spencerharro** [comment]
This would work well.  Better than I was envisioning.

**Comment by sfreder** [comment]
I will add this naming procedure to the signal processing code to create these folders.

**Comment by sfreder** [comment]
When merge #56 is done this issue can be closed.  The rest of the folder naming code will be completed with the data comparison issue.
