### ISSUE TITLE
Poll() data validation

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#49]
Multiple app pages include labels that `poll()` the ava directory for changes to data.json, data1.json, and data2.json.  Need to include data validation so that polling for this data does not throw errors.

**Comment by spencerharro** [comment]
Working on this 3-22-17

**Comment by spencerharro** [comment]
See #60

**Comment by sfreder** [comment]
@spencerharro is this complete?

**Comment by spencerharro** [comment]
Added some validation - enough for now, can add more later.
