### ISSUE TITLE
Add json files to .gitignore

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#52]
We've probably all had difficulty with this - every merge seems to update the .json app status files and vehicle profiles.  Need to either add these files to .gitignore or not include them in commits.

However, if .gitignore - if the app uses new json files, we need those new files to be updated for everyone.  Maybe a selective .gitignore (like our personal vehicle profiles, and selected_vehicle.json, and some of the data, data1, data2 files).

Thoughts?

**Comment by sfreder** [comment]
In the future I will leave the .json files out of my commits unless changes are necessary for the new version to work.

**Comment by spencerharro** [comment]
Complete
