### ISSUE TITLE
Add data collection code to Test_Is_Running_Page backend

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#6]
Implement data collection code for Test_Is_Running_Page backend.

Create timer for delay, when test starts, when test completes.

Show percent completion (decide on bar, % number, or another way).

**Comment by sfreder** [comment]
added sampling code to Configure page.  Need to add information about test status (time remaining) and the initial sensor connection test.

**Comment by sfreder** [comment]
Created two new files that will display progress bars while waiting for the test to begin and while the test is running.  Still working out bugs for the progress bar while test is running.  Data collection is working the raw vibration data is currently placed in a temp folder.

**Comment by sfreder** [comment]
Some bugs and enhancements remain to be done.  Still, this can be considered complete.

**Comment by sfreder** [comment]
Work for this issue was performed on the branch: data-collection
