### ISSUE TITLE
Build raw data plot

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#62]
Include option to view raw data FFT

**Comment by spencerharro** [comment]
@sfreder I'm unsure how to best approach this.  I see in `Signal_Process.py` that this is the procedure for the averaged FFT from start to finish.  Would you be able to point me in the right direction for modifying this to remove the averaging and simply produce a raw plot?

```
# calculate weighted average of fft
        n = 256                                             # number of points in the FFT
        strt = 1
        fnsh = n
        runav = 16                                          # number of FFT's in 8 second weighted average
        smpl = mag[strt:fnsh]

        # first FFT is outside the average loop so we aren't dividing by zero
        freq=numpy.absolute(numpy.fft.rfft(smpl))
        freq[0] = 0

        # until we have done 16 FFT's it is a simple average
        for j in range(1, runav):
            strt = fnsh+1
            fnsh = fnsh+n
            smpl = mag[strt:fnsh]
            freq1=numpy.absolute(numpy.fft.rfft(smpl))
            freq1[0] = 0
            freq = ((freq*j) + freq1)/(j+1)

        # weighted average until end of samples
        while (fnsh+n) < len(mag):
            strt = fnsh+1
            fnsh = fnsh+n
            smpl = mag[strt:fnsh]
            freq1=numpy.absolute(numpy.fft.rfft(smpl))
            freq1[0] = 0
            freq = ((freq*runav) + freq1)/(runav+1)

        # normalize fft
        s = numpy.sum(freq)
        norm = s/(len(freq))
        freq = freq / norm

        # write output to file with frequency scale
        filename2 = path2 + 'fft 250Hz.txt'
        for i in range(0, int(n/2)):
            j = i+1
            hz = float("{0:.1f}".format(j * 500/n))
            enrg = str(hz) + ' ' + str(float("{0:.2f}".format(freq[i]))) + '\n'
            with open(filename2, 'a') as out:
                out.write(enrg)
        f.close
```

**Comment by sfreder** [comment]
I'm not sure what you would like to plot.  If the fft was not averaged there would be 96 individual 128 point fft's per minute each covering about half a second of vehicle vibrations.

**Comment by beleson** [comment]
I am speculating on Spencer's motives - I think time averaged is fine but he is trying to have non-normalized values so that actual energy of the signal can be depicted.  Am I close, Spencer?

**Comment by sfreder** [comment]
My mistake. I got it. Just a moment.  I'm working on this file on branch Process/Compare_loop. Once I commit my changes I suggest you look at the normalize fft section.  if you take the value in the variable freq before the normalize fft section and place it in a new variable that should be the data you are looking for.

**Comment by spencerharro** [comment]
I opened this issue during last Wednesday's Skype call when we talked about including the averaged FFTs along with a potential raw data plot.  I don't think it _has_ to be included (maybe an if we have time feature), but I thought that if it adds benefit it should be relatively easy to code.

**Comment by sfreder** [comment]
You are just looking for an fft average that has not been normalized right?

**Comment by spencerharro** [comment]
Right
