### ISSUE TITLE
New Profile Page functionality

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#66]
I think part of the confusion that can crop up on the New/Edit Profile Page is the text on the button controls.  As it stands now:

- Load active profile values
- Save entered values to profile

Here is an alternative idea:
- Clear
- Prepopulate
- Save
 
Another consideration - it would be convenient to know what action (Edit or make New) the user wants to take before they get to this page.  In this way, the page could automatically clear out all fields with the "New" action and prepopulate fields with the "Edit" action.  However, it does add an additional button to the Home Page.

Any thoughts on a preferred strategy @sfreder @beleson @jdgeyer9?  I will be responsible for coding based on our decision.

**Comment by spencerharro** [comment]
Been working on this most of today.  Getting @beleson's code merged into develop.  Testing on my local repo first.

**Comment by sfreder** [comment]
I think this is done
