### ISSUE TITLE
Test Running Page Layout

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#7]
Fix Test_Is_Running_Page appearance and layout.  Padding, anchor, grid, etc.

**Comment by sfreder** [comment]
Working on hiding the save button until the test is complete.

**Comment by sfreder** [comment]
I am opening a branch for this issue. I still want the save button to hide until the test is done.

**Comment by sfreder** [comment]
this is not working the way I had hoped. Now I am attempting to combine the sample and delay Bar files so that the save button will be covered up by a progress bar for the duration of the test.

**Comment by sfreder** [comment]
I have not been able to work out how to keep the save button hidden until the end of the test. @Huskerbrian I saw something you mentioned about binding and greying things out.  Let me know if you can help with this little issue.  There is no branch for this issue at the moment

**Comment by spencerharro** [comment]
@sfreder From what I can tell, disabling a control can happen like `state = "disabled"`

<img width="642" alt="screen shot 2017-03-23 at 7 41 02 pm" src="https://cloud.githubusercontent.com/assets/13437563/24274759/babea95c-1000-11e7-8e77-3325551146ac.png">

**Comment by spencerharro** [comment]
It looks like he can reconfigure the state in a function bound to the radiobuttons. 
<img width="384" alt="screen shot 2017-03-23 at 7 43 09 pm" src="https://cloud.githubusercontent.com/assets/13437563/24274791/f9856504-1000-11e7-96cf-6fedad062cc9.png"> 
 **and then**
<img width="687" alt="screen shot 2017-03-23 at 7 44 04 pm" src="https://cloud.githubusercontent.com/assets/13437563/24274800/1b8ea2dc-1001-11e7-85eb-515a8523e444.png">

**Comment by sfreder** [comment]
Can we use this to grey out a button until the test is done?

**Comment by spencerharro** [comment]
Yes, I think we can.

**Comment by spencerharro** [comment]
Wait - it would grey the button out making it invalid. But not get rid of
it totally. If you want total removal, might need to look for another Tk
function.

**Comment by sfreder** [comment]
Grey out is all that is needed so that the user can't save the test while the test is still running.

**Comment by sfreder** [comment]
I'm going to get this stupid button taken care of today.
