### ISSUE TITLE
Working app (after merges)

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#70]
@sfreder I merged 3 out of 4 of yesterday's pull requests into develop.  When I pulled down the updates I had a bunch of errors from my files being improperly formatted (since I did not push up all the App_Data files in the commits).

In the folder below are properly initialized json files that should run correctly (you can use combination of these files in your local repo).  Just modify directory.json as usual.

I also tried to push most of the changes up to `develop`.  Save a backup of your local develop branch (in a side folder), then pull changes (to avoid overwriting something you need) because the latest updates change several files.  I included the updated App_Data directory for everyone's convenience in `develop`.

Let me know if you run into challenges.  I can help you get unstuck with several different versions of the files I have backed up.

[ava 5.zip](https://github.com/vibrainium-analytics/ava/files/870823/ava.5.zip)

**Comment by spencerharro** [comment]
This too

[selected_vehicle.json.zip](https://github.com/vibrainium-analytics/ava/files/870777/selected_vehicle.json.zip)

**Comment by spencerharro** [comment]
[ava 3.zip](https://github.com/vibrainium-analytics/ava/files/870811/ava.3.zip)

**Comment by sfreder** [comment]
comment posted in error

**Comment by spencerharro** [comment]
Is file save operational?

**Comment by sfreder** [comment]
Yes file save works. I created a new profile for my car and entered the basic and advanced information.  No problems there.  Data on the plot screen does not update.

**Comment by spencerharro** [comment]
The plot itself, data in the dropdowns, or all of that?

**Comment by beleson** [comment]
Speed is at zero.  I chased this for longer than I care to admit.
