### ISSUE TITLE
Finalize Post-test Questions

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#8]
Finalize list of post-test questions:
- AC on/off
- Under idle?
- Speed (if steady)
...
- etc....(comment below)

**Comment by sfreder** [comment]
Created some data validation that ignores AC if a steady speed test is performed and also changes speed to zero if an idle test is performed.

**Comment by beleson** [comment]
Brian to add gear ratio in post-test questions

**Comment by spencerharro** [comment]
@beleson Is this a basic dropdown with integers 1-#gears or something?  If so I can quickly knock this one out.

**Comment by sfreder** [comment]
If gear ratio is in the vehicle profile then it doesn't need to be in the post test questions right?

**Comment by spencerharro** [comment]
Good point. No we don't

**Comment by beleson** [comment]
No different than the speed.  You need to know what gear you performed the
test in.

**Comment by spencerharro** [comment]
@beleson I think you're right.  I jumped too fast at "gear ratio" without realizing the "ratio" part.

**Comment by spencerharro** [comment]
@beleson Is it an easy dropdown like mentioned above?  I can put that in.

**Comment by sfreder** [comment]
With an automatic transmission do you ever know what gear you are in?
