### ISSUE TITLE
Test naming

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#87]
As we start practicing for the demo video, it probably will be helpful to have a window that pops up allowing the user to save the vehicle data with a specific name.  Then the vehicle data does not have to be manually named.  Is this a good idea, or maybe unnecessary?

**Comment by sfreder** [comment]
So are you envisioning three drop downs containing a list of vehicle makes, models, and years?

**Comment by spencerharro** [comment]
Actually, I was thinking about the tag that describes the diagnostic
trouble cases. Would just be a text box where user puts "low tire" or
something.

**Comment by sfreder** [comment]
So you want the user to put in what they think the trouble is before they start the test?  Or are you talking about how to update unknown trouble files?

**Comment by spencerharro** [comment]
Referring to this.  I was thinking the user had to manually rename the file to reflect low_tire, unbalanced_tire, etc.  How does that identifying tag get added to the file at this point?  Is it automatic or manual?

![screen shot 2017-04-06 at 8 14 00 pm](https://cloud.githubusercontent.com/assets/13437563/24780462/977cb686-1b05-11e7-93dc-4c266b66e5cf.png)

**Comment by spencerharro** [comment]
Wait - that would have to be manual since it is for comparison, which makes total sense - the user doesn't know what the problem is theoretically until they examine the plots.  Having a textbox would not make much sense then...

**Comment by sfreder** [comment]
I did open up #73 to think about other ways to rename the files that did not require the user to open up file manager.
