### ISSUE TITLE
Cut out comparison code

### ISSUE THREAD

**Issue by spencerharro** [vibrainium-analytics/ava#94]

**Comment by sfreder** [comment]
@spencerharro I will send all the new data I have tomorrow. along with some screen shots so that you know what to look for.

**Comment by spencerharro** [comment]
You could even just bundle the data in a zip and I can add it in

**Comment by sfreder** [comment]
here is the batch of data from yesterday's tests.  
[Steve_Corolla_2008.zip](https://github.com/vibrainium-analytics/ava/files/907822/Steve_Corolla_2008.zip)

**Comment by sfreder** [comment]
The code needs to be written to only compare the locations of the peaks and not the magnitude.  This should compensate for different sensor mounting positions and different vehicles. I will work on this next.

**Comment by sfreder** [comment]
I am opening a branch to work on this
